import pptxgen from "pptxgenjs"

// ---------- Color Themes ----------
const THEMES = {
    midnight: {
        titleBg: "0F172A",
        titleAccent: "38BDF8",
        titleText: "FFFFFF",
        subtitleText: "94A3B8",
        slideBg: "0F172A",
        headingText: "38BDF8",
        bodyText: "E2E8F0",
        accent: "38BDF8",
        footerText: "64748B"
    },
    sunset: {
        titleBg: "7C2D12",
        titleAccent: "FB923C",
        titleText: "FFFFFF",
        subtitleText: "FED7AA",
        slideBg: "1C1917",
        headingText: "FB923C",
        bodyText: "FAFAF9",
        accent: "F97316",
        footerText: "A8A29E"
    },
    forest: {
        titleBg: "064E3B",
        titleAccent: "34D399",
        titleText: "FFFFFF",
        subtitleText: "A7F3D0",
        slideBg: "F0FDF4",
        headingText: "065F46",
        bodyText: "1F2937",
        accent: "10B981",
        footerText: "6B7280"
    },
    royal: {
        titleBg: "312E81",
        titleAccent: "A78BFA",
        titleText: "FFFFFF",
        subtitleText: "C4B5FD",
        slideBg: "FFFFFF",
        headingText: "4C1D95",
        bodyText: "1F2937",
        accent: "8B5CF6",
        footerText: "6B7280"
    },
    coral: {
        titleBg: "9D174D",
        titleAccent: "FB7185",
        titleText: "FFFFFF",
        subtitleText: "FBCFE8",
        slideBg: "FFF1F2",
        headingText: "9D174D",
        bodyText: "1F2937",
        accent: "F43F5E",
        footerText: "78716C"
    },
    ocean: {
        titleBg: "0C4A6E",
        titleAccent: "38BDF8",
        titleText: "FFFFFF",
        subtitleText: "BAE6FD",
        slideBg: "F0F9FF",
        headingText: "0C4A6E",
        bodyText: "1F2937",
        accent: "0EA5E9",
        footerText: "64748B"
    }
}

const pickTheme = (name) => {
    if (name && THEMES[name]) return THEMES[name]
    const keys = Object.keys(THEMES)
    return THEMES[keys[Math.floor(Math.random() * keys.length)]]
}

export const generatePpt = async (data) => {

    const T = pickTheme(data.theme) // data.theme optional; warna random amazing theme

    const ppt = new pptxgen()
    ppt.layout = "LAYOUT_WIDE"
    ppt.author = "CortexAI"
    ppt.title = data.title
    ppt.subject = data.title
    ppt.company = "CortexAI"
    ppt.revision = "1"

    ppt.theme = {
        headFontFace: "Aptos",
        bodyFontFace: "Aptos",
        lang: "en-us"
    }

    // ---------- Title Slide ----------
    const titleSlide = ppt.addSlide()
    titleSlide.background = { color: T.titleBg }

    // decorative accent bar
    titleSlide.addShape("rect", {
        x: 0, y: 0, w: 0.18, h: "100%",
        fill: { color: T.titleAccent }
    })

    // decorative circle accents (adds visual "wow")
    titleSlide.addShape("ellipse", {
        x: 10.8, y: -1.2, w: 3.2, h: 3.2,
        fill: { color: T.titleAccent, transparency: 80 }
    })
    titleSlide.addShape("ellipse", {
        x: -1, y: 5, w: 2.4, h: 2.4,
        fill: { color: T.titleAccent, transparency: 85 }
    })

    titleSlide.addText(data.title, {
        x: 0.8, y: 2.2, w: "85%", h: 1.2,
        fontSize: 40,
        bold: true,
        color: T.titleText,
        align: "left",
        fontFace: "Aptos"
    })

    if (data.subtitle) {
        titleSlide.addText(data.subtitle, {
            x: 0.8, y: 3.4, w: "80%", h: 0.8,
            fontSize: 18,
            color: T.subtitleText,
            align: "left",
            fontFace: "Aptos"
        })
    }

    titleSlide.addText("Generated by CortexAI", {
        x: 0.8, y: "90%", w: "80%", h: 0.4,
        fontSize: 12,
        color: T.subtitleText,
        align: "left",
        fontFace: "Aptos"
    })

    // ---------- Content Slides ----------
    data?.slides?.forEach((s, i) => {
        const slide = ppt.addSlide()
        slide.background = { color: T.slideBg }

        // top accent bar
        slide.addShape("rect", {
            x: 0, y: 0, w: "100%", h: 0.12,
            fill: { color: T.accent }
        })

        // slide number chip
        slide.addShape("ellipse", {
            x: 12.2, y: 0.35, w: 0.5, h: 0.5,
            fill: { color: T.accent }
        })
        slide.addText(String(i + 1), {
            x: 12.2, y: 0.35, w: 0.5, h: 0.5,
            fontSize: 14,
            bold: true,
            color: "FFFFFF",
            align: "center",
            valign: "middle",
            fontFace: "Aptos"
        })

        slide.addText(s.title, {
            x: 0.5, y: 0.5, w: "80%", h: 0.8,
            fontSize: 28,
            bold: true,
            color: T.headingText,
            fontFace: "Aptos"
        })

        const bulletText = (s.points || []).map((p) => ({
            text: p,
            options: {
                bullet: { code: "25CF", color: T.accent },
                breakLine: true,
                color: T.bodyText,
                fontSize: 18
            }
        }))

        slide.addText(bulletText, {
            x: 0.6, y: 1.6, w: "85%", h: "68%",
            fontFace: "Aptos",
            valign: "top",
            lineSpacingMultiple: 1.35
        })
    })

    const buffer = await ppt.write({ outputType: "nodebuffer" })
    return buffer
}